server:
  port: 8081

#spring:
#  redis:
#    host: localhost
#    password:
#    port: 6379

beverage:
  jwt:
    keystore:
      path: keystores/beverage.jks
      password: 654321
      keypair-alias: beverage
